version: '3.4'

networks:
  karma-network:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'M0h@mm@d'
    ports:
      - '1434:1433'
    networks:
      - karma-network

  karma.api:
    image: karmaapi:latest
    container_name: karma-api
    ports:
      - '4030:80'
    environment:
      SQL_Host: 'mssql'
      SQL_Username: 'sa'
      SQL_Password: 'M0h@mm@d'
    networks:
      - karma-network
    depends_on:
      - mssql
